spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ecommerce?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update   